name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Run compose down container
      #   run: docker-compose down
      - name: Run compose up container
        run: docker-compose --build -d -f docker-compose.yaml up
